name: sufi_ishq
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  package_info_plus:
  flutter_svg: ^1.1.6
  floor:
  flutter_lints:
  intl: ^0.17.0
dev_dependencies:
  floor_generator:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu_r.ttf
          weight: 300
        - asset: assets/fonts/ubuntu_m.ttf
          weight: 500
        - asset: assets/fonts/ubuntu_b.ttf
          weight: 700

