# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Web App CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
      
      - name: Write compile time firebase_options.dart file
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: echo "$FIREBASE_OPTIONS" | base64 -d > lib/firebase_options.dart
        
      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@v1
      
      # - name: Get dart dependencies
        # run: dart pub get

      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  

      - name: Get flutter dependencies
        run: flutter pub get

      - name: Check for any formatting issues in the code.
        run: dart format --set-exit-if-changed .
    
      - name: Statically analyze the Dart code for any errors.
        run: dart analyze .
        
      - name: Run flutter test
        run: flutter test --coverage
        
      - name: Build
        run: flutter build web
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
