# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
      
      # The flutter action needs java so include it
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      # Include the flutter action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'  

      - name: Get flutter
        run: flutter pub get
     
      - name: Write compile time firebase_options.dart file
        env:
          FIREBASE_OPTIONS: ${{ secrets.FIREBASE_OPTIONS_DART }}
        run: echo $FIREBASE_OPTIONS > lib/firebase_options.dart
      
      - name: Run flutter test
        run: flutter test
        
      - name: Build
        run: flutter build web
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
